### ISSUE TITLE
Calling `list_outputs` before `final_setup` may cause error

### ISSUE THREAD

**Issue by A-CGray** [OpenMDAO/OpenMDAO#3560]
### Description

In one of my MPhys models, I get the following error when calling `list_outputs` directly after `setup` and running in parallel

```
Traceback (most recent call last):
  File "/home/ali/repos/AerostructuralOptBenchmark/runscripts/aeroStructRun-MultipointParallel.py", line 750, in <module>
    tmp = ptComm.bcast(flightPointProb.model.list_outputs(out_stream=None), root=0)
  File "/home/ali/repos/OpenMDAO/openmdao/core/system.py", line 4483, in list_outputs
    outputs = self.get_io_metadata(('output',), keys, includes, excludes,
  File "/home/ali/repos/OpenMDAO/openmdao/core/system.py", line 3898, in get_io_metadata
    dist_vals = [m['val'] for m in allproc_metas
  File "/home/ali/repos/OpenMDAO/openmdao/core/system.py", line 3899, in <listcomp>
    if m is not None and m['val'].size > 0]
AttributeError: 'float' object has no attribute 'size'
```

The specific output that causes the failure is a distributed output that is shaped by connection, using some good old print statements, I can see that at the time of the error the value of the output (on at least one proc) is 1,0:

```python
allproc_metas=[{'val': 1.0}, {'val': 1.0}]
```

Using git bisect, I was able to track the introduction of this issue to commit https://github.com/OpenMDAO/OpenMDAO/commit/62967bd0d5de8197b9de29925e7ecb5f62da628e#diff-5545bcee157fc878e12c8cccee1a1386344ecdf769d7cbbcdcb5c1ce6b59415a

This commit moved calls to `self._setup_dynamic_shapes()` and `self._setup_var_sizes()` from `setup` to `final_setup`. Sure enough, if I call `final_setup` before `list_outputs` this issue goes away.

### Example

```python
"""
A simple OpenMDAO model demonstrating a component with a distributed input
whose shape is determined by its connection from another component's output.
"""

import numpy as np
import openmdao.api as om


class SourceComponent(om.ExplicitComponent):
    """
    A simple component that acts as the source for a distributed variable.
    """

    def setup(self):
        self.add_output("y", shape=10, distributed=True)

    def compute(self, inputs, outputs):
        num_nodes = self.options["num_nodes"]
        outputs["y"] = np.arange(num_nodes, dtype=float) * 2.0


class DistributedComponent(om.ExplicitComponent):
    """
    This component has a distributed input. Its shape is not defined here
    but is inferred from the source of the connection during the setup phase.
    """

    def setup(self):
        self.add_input("x", distributed=True, shape_by_conn=True)

        self.add_output("sum_x", distributed=True, copy_shape="x")

    def compute(self, inputs, outputs):
        outputs["sum_x"] = np.sum(inputs["x"])


# --- Assemble the Model ---
# Create a Group to contain and connect the components.
class MyModel(om.Group):
    def setup(self):
        self.add_subsystem("source_comp", SourceComponent(), promotes_outputs=["y"])
        self.add_subsystem("distributed_comp", DistributedComponent(), promotes_inputs=["x"])
        self.connect("y", "x")


if __name__ == "__main__":
    # --- Setup and Run the Problem ---
    prob = om.Problem(model=MyModel())
    prob.setup()
    prob.model.list_outputs()
```

### OpenMDAO Version

3.34.0 and later
